[uwsgi]
chdir=/home/supriyo/work/testyard/testyard/skillstest
module=skillstest.wsgi:application
home=/home/supriyo/work/testyard/pyenv
master=true
processes=10
pidfile=/tmp/testyard_uwsgi.pid
socket=/home/supriyo/work/testyard/testyard/skillstest/skillstest.sock
vacuum=true
max-requests=5000
daemonize=/var/log/uwsgi/testyard.log
env="HTTPS=on"

