from django.conf.urls import patterns, include, url
from django.conf import settings
from django.views.generic import RedirectView
from skillstest import settings as mysettings
import skillstest.utils as skillutils


# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    (r'/static/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': mysettings.STATIC_ROOT}),

)

urlpatterns += patterns('',
    (r'/media/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': mysettings.MEDIA_ROOT}),

)

urlpatterns += patterns('',
    # Examples:
    # url(r'^$', 'skillstest.views.home', name='home'),
    # url(r'^skillstest/', include('skillstest.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^skillstest/admin/$', include(admin.site.urls)),

    url(r'^%s$'%mysettings.ROOT_URL, 'skillstest.views.returnRedirect', name='returnRedirectRoot'),
    url(r'^$', 'skillstest.views.returnRedirect', name='returnRedirectEmpty'),
    url(r'^%s'%mysettings.HTTP_URL, 'skillstest.views.returnRedirect', name='returnRedirectHttp'),

    url(r'^%s$'%mysettings.REGISTER_URL, 'skillstest.Auth.views.register', name='newuser'),
    url(r'^%s$'%mysettings.DASHBOARD_URL, 'skillstest.views.dashboard', name='dashboard'),
    url(r'^%s$'%mysettings.INDEX_URL, 'skillstest.views.index', name='index'),
    url("%s$"%mysettings.LOGIN_URL, 'skillstest.Auth.views.login', name='login'),
    url("/%s$"%mysettings.LOGIN_URL, 'skillstest.Auth.views.login', name='login2'),
    url(r'%s$'%mysettings.LOGIN_REDIRECT_URL, 'skillstest.views.profile', name='profile'),
    url(r'%s$'%mysettings.GOOGLE_INFO_URL, 'skillstest.Auth.views.storegoogleuserinfo', name='storegoogleuserinfo'),
    url(r'%s$'%mysettings.GOOGLE_LOGIN_URL, 'skillstest.Auth.views.storegoogleuserinfo', name='storegooglelogin'),
    url(r'%s$'%mysettings.LINKEDIN_REDIRECT_URL, 'skillstest.Auth.views.linkedinauthcallback', name='linkedinauthcallback'),
    url(r'%s$'%mysettings.FACEBOOK_REDIRECT_URL, 'skillstest.Auth.views.facebookauthcallback', name='facebookauthcallback'),
    url(r'%s$'%mysettings.FORGOT_PASSWD_URL, 'skillstest.Auth.views.sendforgotpasswdemail', name='sendforgotpasswdemail'),
    url(r'%s$'%mysettings.RESET_PASSWORD, 'skillstest.Auth.views.resetpassword', name='resetpassword'),
    url(r'%s$'%mysettings.AUTOCOMPLETE_COUNTRIES_URL, 'skillstest.views.getcountrieslist', name='getcountrieslist'),
    url(r'%s$'%mysettings.SUBSCRIPTION_URL, 'skillstest.Subscription.views.subscriptions', name='subscriptions'),
    url(r'%s$'%mysettings.PROFILE_URL, 'skillstest.views.profile', name='profile'),
    url(r'%s$'%mysettings.LOGOUT_URL, 'skillstest.views.logout', name='logout'),
    url(r'%s$'%mysettings.MANAGE_TEST_URL, 'skillstest.Tests.views.manage', name='managetests'),
    url(r'%s$'%mysettings.CREATE_TEST_URL, 'skillstest.Tests.views.create', name='createtests'),
    url(r'%s$'%mysettings.EDIT_TEST_URL, 'skillstest.Tests.views.edit', name='edittests'),
    url(r'%s$'%mysettings.EDIT_CHALLENGE_URL, 'skillstest.Tests.views.editchallenge', name='editchallenge'),
    url(r'%s$'%mysettings.TEST_SUMMARY_URL,'skillstest.Tests.views.testsummary', name='testsummary'),
    url(r'%s$'%mysettings.VIEW_TEST_URL,'skillstest.Tests.views.viewtest', name='viewtest'),
    url(r'%s$'%mysettings.GET_SECTION_URL,'skillstest.Tests.views.getsectiondata', name='getsectiondata'),
    url(r'%s$'%mysettings.DELETE_CHALLENGE_URL, 'skillstest.Tests.views.deletechallenges', name='deletechallenges'),
    url(r'%s$'%mysettings.SAVE_CHANGES_URL,'skillstest.Tests.views.savechanges', name='savechanges'),
    url(r'%s$'%mysettings.SHOW_USER_VIEW_URL,'skillstest.Tests.views.showuserview', name='showuserview'),
    url(r'%s$'%mysettings.EDIT_EXISTING_TEST_URL,'skillstest.Tests.views.editexistingtest', name='editexistingtest'),
    url(r'%s$'%mysettings.SEND_TEST_INVITATION_URL,'skillstest.Tests.views.sendtestinvitations', name='sendtestinvitations'),
    url(r'%s$'%mysettings.SEND_TEST_DATA_URL,'skillstest.Tests.views.gettestdata', name='gettestdata'),
    url(r'%s$'%mysettings.MANAGE_INVITATIONS_URL,'skillstest.Tests.views.manageinvitations', name='manageinvitations'),
    url(r'%s$'%mysettings.SHOW_TEST_CANDIDATE_MODE_URL,'skillstest.Tests.views.showtestcandidatemode', name='showtestcandidatemode'),
    url(r'%s$'%mysettings.INVITATION_ACTIVATION_URL,'skillstest.Tests.views.invitationactivation', name='invitationactivation'),
    url(r'%s$'%mysettings.INVITATION_CANCEL_URL,'skillstest.Tests.views.invitationcancellation', name='invitationcancellation'),
    url(r'%s$'%mysettings.ADD_MORE_URL,'skillstest.Tests.views.addmorechallenges', name='addmorechallenges'),
    url(r'%s$'%mysettings.SEARCH_URL, 'skillstest.AdvSearch.views.advsearch', name='advsearch'),
    url(r'%s$'%mysettings.TESTS_CHALLENGE_SEARCH_URL, 'skillstest.AdvSearch.views.testschallengesearch', name='testschallengesearch'),
    url(r'%s$'%mysettings.GROUP_SEARCH_URL, 'skillstest.AdvSearch.views.groupsearch', name='groupsearch'),
    url(r'%s$'%mysettings.GROUP_DATA_URL, 'skillstest.AdvSearch.views.getgroupdata', name='getgroupdata'),
    url(r'%s$'%mysettings.USER_SEARCH_URL, 'skillstest.AdvSearch.views.usersearch', name='usersearch'),
    url(r'%s$'%mysettings.SEARCH_TEST_INFO_URL, 'skillstest.AdvSearch.views.testinfosearch', name='testinfosearch'),
    url(r'%s$'%mysettings.DISPLAY_SEARCHED_CHALLENGES_URL, 'skillstest.AdvSearch.views.displaychallenges', name='displaychallenges'),
    url(r'%s$'%mysettings.CLEAR_NEGATIVE_SCORE_URL, 'skillstest.Tests.views.clearnegativescoreurl', name='clearnegativescoreurl'),
    url(r'%s$'%mysettings.DELETE_TEST_URL,'skillstest.Tests.views.deletetest', name='deletetesturl'),
    url(r'%s$'%mysettings.NETWORK_URL, 'skillstest.Network.views.network', name='network'),
    url(r'%s$'%mysettings.ANALYTICS_URL, 'skillstest.Analytics.views.analytics', name='analytics'),
    url(r'%s$'%mysettings.ABOUTUS_URL, 'skillstest.views.aboutus', name='aboutus'),
    url(r'%s$'%mysettings.HELP_URL, 'skillstest.views.helpndocs', name='helpndocs'),
    url(r'%s$'%mysettings.CAREER_URL, 'skillstest.views.careers', name='careers'),
    url(r'%s$'%mysettings.PLANS_URL, 'skillstest.views.plansnpricing', name='plansnpricing'),
    url(r'%s$'%mysettings.availabilityURL, 'skillstest.Auth.views.checkavailability', name='checkavailability'),
    url(r'%s$'%mysettings.ACCTACTIVATION_URL, 'skillstest.Auth.views.acctactivation', name='acctactivation'),
    url(r'%s$'%mysettings.PROFIMG_CHANGE_URL[1:], 'skillstest.views.profileimagechange', name='profileimagechange'),
    url(r'%s$'%mysettings.TEST_EVALUATION_URL, 'skillstest.Tests.views.evaluate', name='evaluate'),
    url(r'%s$'%mysettings.SHOW_ALL_EMAILS_URL, 'skillstest.Tests.views.showallemailids', name='showallemailids'),
    url(r'%s$'%mysettings.UPDATE_SCHEDULE_URL, 'skillstest.Tests.views.updateschedule', name='updateschedule'),
    url(r'%s$'%mysettings.EVALUATE_RESPONSE_URL, 'skillstest.Tests.views.evaluateresponses', name='evaluateresponses'),
    url(r'%s$'%mysettings.SHOW_EVAL_SCREEN, 'skillstest.Tests.views.showevaluationscr', name='showevaluationscr'),
    url(r'%s$'%mysettings.GET_CURRENT_EVALUATION_DATA_URL, 'skillstest.Tests.views.getevaluationdetails', name='getevaluationdetails'),
    url(r'%s$'%mysettings.TEST_BULK_UPLOAD_URL, 'skillstest.Tests.views.createtestbulkupload', name='createtestbulkupload'),
    url(r'%s$'%mysettings.SHOW_TEST_INFO_URL, 'skillstest.Tests.views.showtestinfo', name='showtestpage'),
    url(r'%s$'%mysettings.SET_VISIBILITY_URL, 'skillstest.Tests.views.setvisibility', name='setvisibility'),
    url(r'%s$'%mysettings.GET_CANVAS_URL, 'skillstest.Tests.views.getcanvas', name='getcanvas'),
    url(r'%s$'%mysettings.GET_AUTOCOMPLETE_LIST_URL, 'skillstest.Tests.views.getautocompletelists', name='getautocompletelists'),
    url(r'%s$'%mysettings.ROLE_BASED_SEARCH_URL, 'skillstest.Tests.views.searchbyrole', name='searchbyrole'),
    url(r'%s$'%mysettings.SAVE_DRAWING_URL, 'skillstest.Tests.views.savedrawing', name='savedrawing'),
    url(r'%s$'%mysettings.DISQUALIFY_CANDIDATE_URL, 'skillstest.Tests.views.disqualifycandidate', name='disqualifycandidate'),
    url(r'%s$'%mysettings.COPY_TEST_URL, 'skillstest.Tests.views.copytest', name='copytest'),
    url(r'%s$'%mysettings.GET_TEST_SCHEDULE_URL, 'skillstest.Tests.views.gettestschedule', name='gettestschedule'),
    url(r'%s$'%mysettings.ACTIVATE_TEST_BY_CREATOR, 'skillstest.Tests.views.activatetestbycreator', name='activatetestbycreator'),
    url(r'%s$'%mysettings.DEACTIVATE_TEST_BY_CREATOR, 'skillstest.Tests.views.deactivatetestbycreator', name='deactivatetestbycreator'),
    url(r'%s$'%mysettings.CAPTURE_AUDIOVISUAL_URL, 'skillstest.Tests.views.captureaudiovisual', name='captureaudiovisual'),
    url(r'%s$'%mysettings.CREATE_INTERVIEW_URL, 'skillstest.Tests.views.createinterview', name='createinterview'),
    url(r'%s$'%mysettings.SHOW_INTERVIEW_SCHEDULE_SCREEN_URL, 'skillstest.Tests.views.displayinterviewschedulescreen', name='displayinterviewschedulescreen'),
    url(r'%s$'%mysettings.SAVE_NEW_INTERVIEW_SCHEDULE_URL, 'skillstest.Tests.views.savenewinterviewschedule', name='savenewinterviewschedule'),
    url(r'%s$'%mysettings.RESCHEDULE_INTERVIEW_URL, 'skillstest.Tests.views.rescheduleinterview', name='rescheduleinterview'),
    url(r'%s$'%mysettings.UPLOAD_RECORDING_URL, 'skillstest.Tests.views.uploadrecording', name='uploadrecording'),
    url(r'%s$'%mysettings.CHECK_INT_NAME_AVAILABILITY_URL, 'skillstest.Tests.views.checknameavailability', name='checknameavailability'),
    url(r'%s$'%mysettings.CHALLENGE_STORE_URL, 'skillstest.Tests.views.interviewchallengestore', name='interviewchallengestore'),
    url(r'%s$'%mysettings.BLOB_UPLOAD_URL, 'skillstest.Tests.views.uploadblobdata', name='uploadblobdata'),
    url(r'%s$'%mysettings.ASK_QUESTION_URL, 'skillstest.Tests.views.askquestion', name='askquestion'),
    url(r'%s'%mysettings.ATTEND_INTERVIEW_URL, 'skillstest.Tests.views.attendinterview', name='attendinterview'),
    url(r'%s$'%mysettings.UPDATE_INTERVIEW_META_URL, 'skillstest.Tests.views.updateinterviewmeta', name='updateinterviewmeta'),
    url(r'%s$'%mysettings.INTERVIEW_DATA_UPLOAD_URL, 'skillstest.Tests.views.uploadinterviewdata', name='uploadinterviewdata'),
    url(r'%s$'%mysettings.LATEX_KEYBOARD_URL, 'skillstest.Tests.views.latexkeyboard', name='latexkeyboard'),
    url(r'%s$'%mysettings.CODEPAD_EXECUTE_URL, 'skillstest.Tests.views.executecodepad', name='executecodepad'),
    url(r'%s$'%mysettings.CODE_EXEC_URL, 'skillstest.Tests.views.executecode', name='executecode'),
    url(r'%s$'%mysettings.REPORT_WINDOW_CHANGE_URL, 'skillstest.Tests.views.reportwindowchange', name='reportwindowchange'),
    url(r'%s$'%mysettings.GET_TIME_REMAINING_URL, 'skillstest.Tests.views.gettimeremaining', name='gettimeremaining'),
    url(r'%s$'%mysettings.CHK_INTERNET_CONN_URL, 'skillstest.Tests.views.chkinternetconnection', name='chkinternetconnection'),
    url(r'%s$'%mysettings.POST_ON_LINKEDIN_URL, 'skillstest.Tests.views.postonlinkedin', name='postonlinkedin'),
    url(r'%s$'%mysettings.LINKEDINPOSTSESS_URL, 'skillstest.Tests.views.linkedinpostinform', name='linkedinpostinform'),
    url(r'%s$'%mysettings.LINKEDIN_REDIRECT_URL, 'skillstest.Tests.views.linkedinredirect', name='linkedinredirect'),
    url(r'%s$'%mysettings.SHOW_EVALUATION_URL, 'skillstest.Tests.views.showevaluationscreen', name='showevaluationscreen'),
    url(r'%s$'%mysettings.CREATE_NETWORK_GROUP_URL, 'skillstest.Network.views.creategroup', name='creategroup'),
    url(r'%s$'%mysettings.CHECK_GRPNAME_AVAIL_URL, 'skillstest.Network.views.checkgrpnameavailability', name='creategroup'),
    url(r'%s$'%mysettings.SEARCH_GROUP_URL, 'skillstest.Network.views.searchgroups', name='searchgroups'),
    url(r'%s$'%mysettings.GET_GROUP_INFO_URI, 'skillstest.Network.views.getgroupinfo', name='getgroupinfo'),
    url(r'%s$'%mysettings.SEND_JOIN_REQUEST_URL, 'skillstest.Network.views.handlejoinrequest', name='handlejoinrequest'),
    url(r'%s$'%mysettings.SEND_GENTLE_REMINDER_URL, 'skillstest.Network.views.sendgentlereminder', name='sendgentlereminder'),
    url(r'%s$'%mysettings.GET_GROUP_DATA_URL, 'skillstest.Network.views.getgroupdata', name='getgroupdata'),
    url(r'%s$'%mysettings.GROUP_IMG_UPLOAD_URL, 'skillstest.Network.views.groupimgupload', name='groupimgupload'),
    url(r'%s$'%mysettings.SAVE_GROUP_DATA_URL, 'skillstest.Network.views.savegroupdata', name='savegroupdata'),
    url(r'%s$'%mysettings.PAYMENT_GW_URL, 'skillstest.Network.views.showpaymentscreen', name='showpaymentscreen'),
    url(r'%s$'%mysettings.SUBSCRIPTION_GW_URL, 'skillstest.Network.views.showsubscriptionpaymentscreen', name='showsubscriptionpaymentscreen'),
    url(r'%s$'%mysettings.PAYU_CONFIRM_URL, 'skillstest.Network.views.confirmpayment_payu', name='confirmpayment_payu'),
    url(r'%s$'%mysettings.STRIPE_CONFIRM_URL, 'skillstest.Network.views.confirmpayment_stripe', name='confirmpayment_stripe'),
    url(r'%s$'%mysettings.STRIPE_ACCT_LINK_REFRESH_URL, 'skillstest.Network.views.accountlinkrefresh_stripe', name='accountlinkrefresh_stripe'),
    url(r'%s$'%mysettings.STRIPE_ACCT_LINK_RETURN_URL, 'skillstest.Network.views.accountlinkreturn_stripe', name='accountlinkreturn_stripe'),
    url(r'%s$'%mysettings.STRIPE_SUCCESS_URL, 'skillstest.Network.views.checkoutsuccess_stripe', name='checkoutsuccess_stripe'),
    url(r'%s$'%mysettings.STRIPE_CANCEL_URL, 'skillstest.Network.views.checkoutcancel_stripe', name='checkoutcancel_stripe'),
    url(r'%s$'%mysettings.RAZORPAY_SUCCESS_URL, 'skillstest.Network.views.checkoutsuccess_razorpay', name='checkoutsuccess_razorpay'),
    url(r'%s$'%mysettings.RAZORPAY_FAILURE_URL, 'skillstest.Network.views.checkoutfailure_razorpay', name='checkoutfailure_razorpay'),
    url(r'%s$'%mysettings.CURRENCY_RATE_URL, 'skillstest.Network.views.getcurrencyrate', name='getcurrencyrate'),
    url(r'%s$'%mysettings.SEARCH_USER_URL, 'skillstest.Network.views.searchuser', name='searchuser'),
    url(r'%s$'%mysettings.SEND_CONNECTION_URL, 'skillstest.Network.views.sendconnectionrequest', name='sendconnectionrequest'),
    url(r'%s$'%mysettings.SAVE_GROUP_JOIN_STATUS_URL, 'skillstest.Network.views.savegroupjoinstatus', name='savegroupjoinstatus'),
    url(r'%s$'%mysettings.GET_MORE_MESSAGES_URL, 'skillstest.Network.views.getmoremessages', name='getmoremessages'),
    url(r'%s$'%mysettings.CONNECTION_INVITE_HANDLER_URL, 'skillstest.Network.views.handleconnectinvitation', name='handleconnectinvitation'),
    url(r'%s$'%mysettings.GET_MORE_JOIN_REQUESTS_URL, 'skillstest.Network.views.getmorejoinrequests', name='getmorejoinrequests'),
    url(r'%s$'%mysettings.LEAVE_GROUP_URL, 'skillstest.Network.views.leavegroup', name='leavegroup'),
    url(r'%s$'%mysettings.WITHDRAWSCREEN_URL, 'skillstest.Network.views.showwithdrawscreen', name='showwithdrawscreen'),
    url(r'%s$'%mysettings.DOWITHDRAWAL_URL, 'skillstest.Network.views.dowithdrawal', name='dowithdrawal'),
    url(r'%s$'%mysettings.LISTEN_AUDIO_URL, 'skillstest.Tests.views.convertspeechtotext', name='convertspeechtotext'),
    url(r'%s$'%mysettings.GROUPIMG_CHANGE_URL, 'skillstest.Network.views.groupimagechange', name='groupimagechange'),
    url(r'%s$'%mysettings.GROUPINFO_SAVE_URL, 'skillstest.Network.views.groupinfosave', name='groupinfosave'),
    url(r'%s$'%mysettings.GROUP_PROFILE_URL, 'skillstest.Network.views.showgroupprofile', name='showgroupprofile'),
    url(r'%s$'%mysettings.EXIT_GROUP_URL, 'skillstest.Network.views.exitgroup', name='exitgroup'),
    url(r'%s$'%mysettings.SHOW_MORE_SUBSCRIBED_GRPS_URL, 'skillstest.Network.views.showmoresubscribedgroups', name='showmoresubscribedgroups'),
    url(r'%s$'%mysettings.SHOW_MORE_CONNECTIONS_URL, 'skillstest.Network.views.showmoreconnections', name='showmoreconnections'),

    url(r'%s$'%mysettings.POST_MESSAGE_CONTENT_URL, 'skillstest.Network.views.postmessagecontent', name='postmessagecontent'),
    url(r'%s$'%mysettings.POST_REPLY_CONTENT_URL, 'skillstest.Network.views.postreplycontent', name='postreplycontent'),
    url(r'%s$'%mysettings.NEXT_POST_LIST_URL, 'skillstest.Network.views.nextpostlist', name='nextpostlist'),
    url(r'%s$'%mysettings.NEW_MESSAGE_READ_URL, 'skillstest.Network.views.newmessageread', name='newmessageread'),
    url(r'%s$'%mysettings.SEND_MSG_RESPONSE_URL, 'skillstest.Network.views.sendmsgresponse', name='sendmsgresponse'),
    url(r'%s$'%mysettings.MESSAGE_SEARCH_URL, 'skillstest.Network.views.msgsearch', name='msgsearch'),
    url(r'%s$'%mysettings.DOWNLOAD_ATTACHMENT_URL, 'skillstest.Network.views.downloadattachment', name='downloadattachment'),
    url(r'%s$'%mysettings.TEST_TO_GROUPS_URL, 'skillstest.Network.views.givetesttogroups', name='givetesttogroups'),
    url(r'%s$'%mysettings.GET_TEST_GROUPS_URL, 'skillstest.Network.views.gettestsandgroups', name='gettestsandgroups'),
    url(r'%s$'%mysettings.GET_CONNECTION_INFO_URL, 'skillstest.Network.views.getconnectioninfo', name='getconnectioninfo'),
    url(r'%s$'%mysettings.GET_GROUPS_OWNED_URL, 'skillstest.Network.views.getgroupsownedinfo', name='getgroupsownedinfo'),
    url(r'%s$'%mysettings.GET_GROUPS_MEMBER_URL, 'skillstest.Network.views.getgroupsmemberinfo', name='getgroupsmemberinfo'),
    url(r'%s$'%mysettings.GET_CONN_DICT_URL, 'skillstest.Network.views.getconnectioninfolevel2', name='getconnectioninfolevel2'),
    url(r'%s$'%mysettings.BLOCK_USER_URL, 'skillstest.Network.views.blockuser', name='blockuser'),
    url(r'%s$'%mysettings.UNBLOCK_USER_URL, 'skillstest.Network.views.unblockuser', name='unblockuser'),
    url(r'%s$'%mysettings.REMOVE_USER_URL, 'skillstest.Network.views.removeuser', name='removeuser'),
    url(r'%s$'%mysettings.SEND_MESSAGE_URL, 'skillstest.Network.views.sendmessage', name='sendmessage'),
    url(r'%s$'%mysettings.MANAGE_GROUP_MEMBERS_URL, 'skillstest.Network.views.managegroupmembers', name='managegroupmembers'),
    url(r'%s$'%mysettings.SAVE_GROUP_MEMBERS_URL, 'skillstest.Network.views.savegroupmembers', name='savegroupmembers'),
    url(r'%s$'%mysettings.MEMBER_SEARCH_URL, 'skillstest.Network.views.searchmember', name='searchmember'),
    url(r'%s$'%mysettings.MANAGE_OWNED_GROUPS_URL, 'skillstest.Network.views.manageownedgroups', name='manageownedgroups'),
    url(r'%s$'%mysettings.MANAGE_POSTS_URL, 'skillstest.Network.views.manageposts', name='manageposts'),
    url(r'%s$'%mysettings.SAVE_POST_INFO_URL, 'skillstest.Network.views.savepostsinfo', name='savepostsinfo'),
    url(r'%s$'%mysettings.SEND_A_MESSAGE_URL, 'skillstest.Network.views.sendamessage', name='sendamessage'),
    url(r'%s$'%mysettings.PAYUMONEY_SUCCESS_URL, 'skillstest.Network.views.payumoneysuccess', name='payumoneysuccess'),
    url(r'%s$'%mysettings.PAYUMONEY_FAILURE_URL, 'skillstest.Network.views.payumoneyfailure', name='payumoneyfailure'),
    url(r'%s$'%mysettings.WEPAY_REGISTER_REDIRECT_URL, 'skillstest.Network.views.wepayoauthredirect', name='wepayoauthredirect'),
    url(r'%s'%mysettings.WEPAY_DUMMY_AUTHORIZE_URL, 'skillstest.Network.views.wepayauthorize', name='wepayauthorize'),

    url(r'%s$'%mysettings.SAVE_OPTIONAL_INFO_URL, 'skillstest.views.saveoptionalinfo', name='saveoptionalinfo'),
    url(r'%s$'%mysettings.SET_TEST_SCHEDULE_URL, 'skillstest.Tests.views.setschedule', name='setschedule'),

    url(r'%s$'%mysettings.DETAIL_HELP_URL, 'skillstest.views.detailedhelp', name='detailedhelp'),

    url(r'%s$'%mysettings.ANALYTICS_URL, 'skillstest.Analytics.views.analytics', name='mainanalytics'),
    url(r'%s$'%mysettings.GET_TESTS_BY_TOPIC_URL, 'skillstest.Analytics.views.gettestsbytopic', name='gettestsbytopic'),
    url(r'%s$'%mysettings.COMPARE_WITH_TOPPERS_URL, 'skillstest.Analytics.views.comparewithtoppers', name='comparewithtoppers'),
    url(r'%s$'%mysettings.COMPARE_WITH_ALL_URL, 'skillstest.Analytics.views.comparewithall', name='comparewithall'),
    url(r'%s$'%mysettings.COMPARE_TOPIC_SCORES_URL, 'skillstest.Analytics.views.comparetopicscores', name='comparetopicscores'),
    url(r'%s$'%mysettings.COMPARE_CHALLENGE_SCORES_URL, 'skillstest.Analytics.views.comparechallengescores',name='comparechallengescores'),
    url(r'%s$'%mysettings.COMPARE_SCORES_MMM_URL, 'skillstest.Analytics.views.comparescoresmmm', name='comparescoresmmm'),
    url(r'%s$'%mysettings.COMPARE_COHORT_URL, 'skillstest.Analytics.views.comparecohort', name='comparecohort'),
    url(r'%s$'%mysettings.COMPARE_SBT_URL, 'skillstest.Analytics.views.comparesbt', name='comparesbt'),
    url(r'%s$'%mysettings.COMPARE_PPT_URL, 'skillstest.Analytics.views.comparescoreperc', name='comparescoreperc'),
    url(r'%s$'%mysettings.COMPARE_TTPERF_URL, 'skillstest.Analytics.views.comparettperf', name='comparettperf'),
    url(r'%s$'%mysettings.COMPARE_PERFT_URL, 'skillstest.Analytics.views.compareperft', name='compareperft'),
    url(r'%s$'%mysettings.COMPARE_PASSFAIL_URL, 'skillstest.Analytics.views.comparepassfail', name='comparepassfail'),
    url(r'%s$'%mysettings.CREATOR_COMPSCORE_URL, 'skillstest.Analytics.views.creatorcompscores', name='creatorcompscores'),
    url(r'%s$'%mysettings.CREATOR_TESTPOP_URL, 'skillstest.Analytics.views.creatortestpopularity', name='creatortestpopularity'),
    url(r'%s$'%mysettings.CREATOR_TESTTIMES_URL, 'skillstest.Analytics.views.creatortesttimes', name='creatortesttimes'),
    url(r'%s$'%mysettings.CREATOR_TESTMMM_URL, 'skillstest.Analytics.views.creatortestmmm', name='creatortestmmm'),
    url(r'%s$'%mysettings.CREATOR_TESTUSAGE_URL, 'skillstest.Analytics.views.creatortestusage', name='creatortestusage'),
    url(r'%s$'%mysettings.CREATOR_TESTCOHORT_URL, 'skillstest.Analytics.views.creatortestcohort', name='creatortestcohort'),
    url(r'%s$'%mysettings.EVALUATOR_DISPLAY_URL, 'skillstest.Analytics.views.evaluatordisplay', name='evaluatordisplay'),
    url(r'%s$'%mysettings.EVALUATOR_PASS_RATIO_URL, 'skillstest.Analytics.views.evaluatorpassratio', name='evaluatorpassratio'),
    url(r'%s$'%mysettings.EVALUATOR_COUNT_TESTS_URL, 'skillstest.Analytics.views.evaluatorcounttests', name='evaluatorcounttests'),
    url(r'%s$'%mysettings.EVALUATOR_ANSTIME_URL, 'skillstest.Analytics.views.evaluatoranswerscriptsbytime', name='evaluatoranswerscriptsbytime'),
    
    url(r'%s$'%mysettings.PLAN_SUBSCRIBE_URL, 'skillstest.Subscription.views.subscribeplan', name='subscribeplan'),
    url(r'%s$'%mysettings.PAYMENT_GW_OPTIONS_URL, 'skillstest.Subscription.views.showpaymentgwoptions', name='showpaymentgwoptions'),
    url(r'%s$'%mysettings.PAYU_NOTIFY_URL, 'skillstest.Subscription.views.payunotify', name='payunotify'),
    url(r'%s$'%mysettings.SUBSCRIBE_PAYPAL_URL, 'skillstest.Subscription.views.subscribepaypal', name='subscribepaypal'),

    url(r'%s$'%mysettings.MOBILE_VERIFY_CREDS_URL, 'skillstest.Auth.views.mobile_verifypassword', name='mobile_verifypassword'),
    url(r'%s$'%mysettings.MOBILE_LIST_TESTS_INTERVIEWS_URL, 'skillstest.Tests.views.mobile_listtestsandinterviews', name='mobile_listtestsandinterviews'),
    url(r'%s$'%mysettings.MOBILE_TEST_CREATE_URL, 'skillstest.Tests.views.mobile_createtest', name='mobile_createtest'),
    url(r'%s$'%mysettings.MOBILE_CHALLENGE_ADDITION_URL, 'skillstest.Tests.views.mobile_addchallenge', name='mobile_addchallenge'),
    url(r'%s$'%mysettings.MOBILE_LIST_CREATOR_TESTS_URL, 'skillstest.Tests.views.mobile_listcreatortests', name='mobile_listcreatortests'),
    url(r'%s$'%mysettings.MOBILE_TEST_SET_SCHEDULE_URL, 'skillstest.Tests.views.mobile_setschedule', name='mobile_setschedule'),
    url(r'%s$'%mysettings.MOBILE_SEARCH_TEST_URL, 'skillstest.Tests.views.mobile_searchtest', name='mobile_searchtest'),
    url(r'%s$'%mysettings.MOBILE_PENDING_TESTS_URL, 'skillstest.Tests.views.mobile_pendingtests', name='mobile_pendingtests'),
    url(r'%s$'%mysettings.MOBILE_OPEN_TEST_URL, 'skillstest.Tests.views.mobile_opentest', name='mobile_opentest'),
    url(r'%s$'%mysettings.MOBILE_CREATE_INTERVIEW_URL, 'skillstest.Tests.views.mobile_createinterview', name='mobile_createinterview'),
    url(r'%s$'%mysettings.MOBILE_LIST_INTERVIEW_URL, 'skillstest.Tests.views.mobile_listinterviews', name='mobile_listinterviews'),
    
    url(r'%s$'%mysettings.GOOGLE_CALENDAR_URL, 'skillstest.Tests.views.addtogooglecalendar', name='addtogooglecalendar'),
    url(r'%s$'%mysettings.GOOGLE_CALENDAR_INTERVIEW_URL, 'skillstest.Tests.views.addinterviewtogooglecalendar', name='addinterviewtogooglecalendar'),
    url(r'%s$'%mysettings.PRIVPOLICY_URL, 'skillstest.views.privacypolicy', name='privacypolicy'),
    url(r'%s$'%mysettings.TERMSOFUSE_URL, 'skillstest.views.termsofuse', name='termsofuse'),
    url(r'%s$'%mysettings.CONTACTTY_URL, 'skillstest.views.contactty', name='contactty'),

    url(r'^.*$', 'skillstest.views.returnRedirect', name='returnRedirectHttp'), # All other URLs are handled here...
)
# https://testyard.in/skillstest/tests/calendarinterview/
# https://testyard.in/skillstest/tests/calendartest/

